export const COUNTRIES = [
  // Africa
  "South Africa",
  "Nigeria",
  "Kenya",
  "Ghana",
  "Zimbabwe",
  "Botswana",
  "Namibia",
  "Zambia",
  "Mozambique",
  "Malawi",
  "Tanzania",
  "Uganda",
  "Rwanda",
  "Ethiopia",
  "Egypt",
  "Morocco",
  "Algeria",
  "Tunisia",
  "Senegal",
  "Ivory Coast",
  "Cameroon",
  "Angola",
  "Democratic Republic of the Congo",
  "Republic of the Congo",
  "Sierra Leone",
  "Liberia",
  "Seychelles",
  "Mauritius",
  "Eswatini",
  "Lesotho",

  // Rest of world
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
];
